DROP TABLE IF EXISTS book_author, book, author, reader, transaction;

CREATE TABLE IF NOT EXISTS book (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_name VARCHAR(200) NOT NULL,
    year_publication INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS author (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    birth_date DATE
);

CREATE TABLE IF NOT EXISTS book_author (
    book_id INTEGER NOT NULL,
    author_id INTEGER NOT NULL,
    PRIMARY KEY (book_id, author_id),
    FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reader (
    phone_number VARCHAR(15) PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender CHAR(1) CHECK (gender IN ('M', 'Ж')),
    birth_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS transaction (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_type VARCHAR(10) CHECK (operation_type IN ('взятие', 'возврат')) NOT NULL,
    operation_date TIMESTAMP NOT NULL,
    reader_phone VARCHAR(15) NOT NULL,
    book_id INTEGER NOT NULL,
    FOREIGN KEY (reader_phone) REFERENCES reader (phone_number) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE
);
